POST http://localhost:3000/api/linkcheckout HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJkaXIiLCJlbmMiOiJBMjU2Q0JDLUhTNTEyIiwia2lkIjoiTHZ5OW5MY3lHX3VrOVU4TkVFbWFudDl3WWpwT0RFSjBkdjMwdlhvU2N3RTNka2FHSnlIVDNPT3R6M1hoM3JzWVdLN05NZXVfSmlhdVNmSDc4TmpSSEEifQ..sW2RR6uZT3l7ThKmu7Bg_Q.oxVU02sNjFreK5yKUGDrTawMXLr3z_Gtu86k2nEInECs6ElLgWUuVRMA-JEtWBbfnRMe8SxNaw-f7L2dAghjb1o8iAop3bLnNvjqbm6X0voo4an5zppJv-qcoVIyxrVizvvBtJOMTwzUqp-vBVeNx_CRUXuhZ2_AHGcWQvUWNZc.Z3o1ukRLk5S5c6ZTH_mOGeXOqy-C5b45kJx7eDLrTn8

{
    "perfumeId": "cma10oz8w000cvu2846aeeew1",
    "type":"whatsapp"
    "links": [
    {
      "type": "whatsapp",
      "link": "https://wa.me/62895349042623?text=Halo,%20saya%20tertarik%20dengan%20parfumnya."
    },
    {
      "type": "shopee",
      "link": "https://shopee.co.id/sample-parfum"
    },
    {
      "type": "tokopedia",
      "link": "https://www.tokopedia.com/sample-parfum"
    }
  ]
}